import { StatusPremium, type IOrder } from 'config/types';

export const tariffData: IOrder[] = [
  {
    orderId: 1,
    name: 'Пробный',
    quantityOfDays: 1,
    messageForBot: 'Cообщение для пробного',
    description: 'Доступ к премиум-подписке на 1 день',
    amount: 300,
    status: StatusPremium.MAIN,
  },
  {
    orderId: 2,
    name: 'Начальный',
    quantityOfDays: 3,
    messageForBot: 'Cообщение для начального',
    description: 'Доступ к премиум-подписке на 3 дня.',
    amount: 700,
    status: StatusPremium.MAIN,
  },
  {
    orderId: 3,
    name: 'Базовый',
    quantityOfDays: 7,
    messageForBot: 'Cообщение для базового',
    description: 'Доступ к премиум-подписке на 7 дней.',
    amount: 1200,
    status: StatusPremium.MAIN,
  },
  {
    orderId: 4,
    name: 'Стандартный',
    quantityOfDays: 15,
    messageForBot: 'Cообщение для стандартного',
    description: 'Доступ к премиум-подписке на 15 дней.',
    amount: 1800,
    status: StatusPremium.MAIN,
  },
  {
    orderId: 5,
    name: 'Оптимальный',
    quantityOfDays: 30,
    messageForBot: 'Cообщение для оптимального',
    description: 'Доступ к премиум-подписке на 30 дней.',
    amount: 2500,
    status: StatusPremium.MAIN,
  },
  {
    orderId: 6,
    name: 'Расширенный',
    quantityOfDays: 90,
    messageForBot: 'Cообщение для расширенного',
    description: 'Доступ к премиум-подписке на 90 дней.',
    amount: 7000,
    status: StatusPremium.MAIN,
  },
  {
    orderId: 7,
    name: 'Долгосрочный',
    quantityOfDays: 180,
    messageForBot: 'Cообщение для долгосрочного',
    description: 'Доступ к премиум-подписке на 180 дней.',
    amount: 12000,
    status: StatusPremium.MAIN,
  },
  {
    orderId: 8,
    name: 'Годовой',
    quantityOfDays: 365,
    messageForBot: 'Cообщение для годового',
    description: 'Доступ к премиум-подписке на 365 дней.',
    amount: 23000,
    status: StatusPremium.MAIN,
  },
];
