version: '3'
services:
  bot:
    build: 
      context: ../
      dockerfile: ./.Docker/bot/Dockerfile
    image: bot
    container_name: patrebna_bot
    restart: always
    ports:
      - "8443:8443"
    depends_on:
      - mongodb
    networks:
      - patrebna-network  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: >
      mongod 
      --tlsMode requireTLS 
      --tlsCertificateKeyFile /etc/ssl/mongodb.pem 
      --tlsCAFile /etc/ssl/ca.pem 
      --auth
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
      - ../certs/mongodb/mongodb.pem:/etc/ssl/mongodb.pem
      - ../certs/ca.pem:/etc/ssl/ca.pem
    networks:
      - patrebna-network

networks:
  patrebna-network:
    driver: bridge